name: Build & Publish Frontend Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU and buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine tag
        id: vars
        run: echo "ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/taskmaster-front:latest
            ${{ secrets.DOCKER_USERNAME }}/taskmaster-front:${{ steps.vars.outputs.ref }}
